### ISSUE TITLE
[MIP-3] Support MQTT protocol version 5

### ISSUE THREAD

**Issue by mattisonchao** [streamnative/mop#369]
## Motivation

Current we just support MQTT protocol version 3.1/3.11 and a part of version 5.

## Goal

Complete support MQTT protocol version 5.

## API Changes

none.

### CONNECT
 - [x] Authentication method @Technoboy- #692
 - [x] Maximum packet size #631 
 - [x] Receive maximum
 - [x] Request problem information  @mattisonchao  https://github.com/streamnative/mop/pull/655
 - [x] Request response information   // Optional feature
 - [x] Session expiry interval
 - [x] Topic alias maximum @mattisonchao  https://github.com/streamnative/mop/pull/686
 - [x] User property
### Last will and testament
- [x] Content type @Technoboy- #666
- [x] Correlation data @Technoboy- #666
- [x] Message expiry interval @Technoboy- #670 
- [x] Payload format indicator @Technoboy- #666
- [x] Response topic @Technoboy- #666
- [x] User property @Technoboy- #632
- [x] Will delay interval @Technoboy- #670 
### CONNACK
- [x] Assigned client identifier
- [x] Authentication data @Technoboy- #692
- [x] Authentication method @Technoboy- #692
- [x] Maximum packet size  @Technoboy- #685
- [x] Maximum qos @Technoboy- #677 
- [x] Reason string
- [x] Receive maximum
- [x] Response information @Technoboy- #677 
- [x] Retain available // For we support retained message, so no need to do.
- [x] Server keep alive
- [x] Server reference // No need to implement, supported
- [x] Session expiry interval
- [x] Shared subscription available
- [x] Subscription identifiers available @Technoboy- #685
- [x] Topic alias maximum @mattisonchao  https://github.com/streamnative/mop/pull/686
- [x] User property
- [x] Wildcard subscription available @mattisonchao  // For we support wildcard subscription, so no need to do.
### PUBLISH
- [x] Content type @Technoboy- #663
- [x] Correlation data @Technoboy- #663
- [x] Message expiry interval @Technoboy- #669 
- [x] Payload format indicator @Technoboy- #666
- [x] Response topic @Technoboy- #663
- [x] Subscription identifier // Currently doesn't have a use case for it. and many clients don't support it yet.
- [x] Topic alias @mattisonchao  https://github.com/streamnative/mop/pull/688
- [x] User property @Technoboy- #658
### PUBACK / PUBREC / PUBREL / PUBCOMP / SUBACK / SUBSCRIBE / SUBACK
- [x] Reason string 
- [x] User property //No need to implement
### SUBSCRIBE
- [x] Subscription identifier //No need to implement
- [x] User property //No need to implement
### DISCONNECT
- [x] Reason string 
- [x] Server reference // No need to implement, supported
- [x] Session expiry interval
- [x] User property
### AUTH @Technoboy- #693 
- [x] Authentication method
- [x] Authentication data
- [x] Reason string
- [x] User property

## Reject Alternatives

none.

**Comment by mattisonchao** [comment]
@Technoboy- 

I will continue work for this after MIP-1.
